version: "3.7"
services:
    bash:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: bash
        entrypoint: /bin/bash
        image: bash
        network_mode: host
        ports:
            - 30303:30303/tcp
            - 30303:30303/udp
        stdin_open: true
        tty: true
    bootnode:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: console
        entrypoint: /bin/bash -c "qrencode -t ANSI 0x$$(cat account.txt) && echo Your account is 0x$$(cat account.txt) && geth --cache 8192 --datadir node --ethash.dagdir node/dag --etherbase $$(cat account.txt) --gasprice 1 --networkid 996544096 --nodekey boot.key --nousb --password password.txt --port 30303 --syncmode fast --unlock $$(cat account.txt) --verbosity 0 console"
        image: console
        network_mode: host
        ports:
            - 30304:30303/tcp
            - 30304:30303/udp
        stdin_open: true
        tty: true
    console:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: console
        entrypoint: /bin/bash -c "qrencode -t ANSI 0x$$(cat account.txt) && echo Your account is 0x$$(cat account.txt) && geth --cache 8192 --datadir node --ethash.dagdir node/dag --etherbase $$(cat account.txt) --gasprice 1 --mine --minerthreads 1 --networkid 996544096 --nousb --password password.txt --port 30303 --syncmode fast --unlock $$(cat account.txt) --verbosity 0 console"
        image: console
        network_mode: host
        ports:
            - 30304:30303/tcp
            - 30304:30303/udp
        stdin_open: true
        tty: true
    node:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: node
        entrypoint: /bin/bash -c "qrencode -t ANSI 0x$$(cat account.txt) && echo Your account is 0x$$(cat account.txt) && geth --cache 8192 --datadir node --ethash.dagdir node/dag --etherbase $$(cat account.txt) --gasprice 1 --mine --minerthreads 1 --networkid 996544096 --nousb --password password.txt --port 30303 --syncmode full --unlock $$(cat account.txt)"
        image: node
        network_mode: host
        ports:
            - 30303:30303/tcp
            - 30303:30303/udp
        stdin_open: true
        tty: true
